WIP Firewatch 1.5
mondoohq/docs pull request #126
Opened 2024-04-24 16:22 UTC by misterpantz

#### Description

#### Related issue

#### Types of changes

- [ ] Functional documentation bug fix (i.e., broken link or some other busted behavior)
- [ ] New functional doc capabilities (i.e., filter search results)
- [ ] New content
- [ ] Revision to existing content
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

#### Checklist

- [ ] I have read the **README** document about contributing to this repo.
- [ ] I have tested my changes locally and there are no issues.
- [ ] All commits are signed.

2024-04-24 16:48 UTC, tas50 requested changes

2024-04-24 16:48 UTC, tas50 commented on docs/platform/security/vuln/vulnerabilities.md
> +| ![In use icon](/img/platform/security/use.png) | **In use** indicates that at least one asset with this CVE has a running service or is in active use. Examples are assets running SSHD, OpenSSH, NGI
This is usually written sshd

2024-04-24 16:48 UTC, tas50 commented on docs/platform/security/vuln/vulnerabilities.md
> +| ![Database icon](/img/platform/security/db.png) | **Database** indicates that at least one asset with this CVE hosts a running database.              |
Can we list the database systems we currently detect here?

2024-04-24 16:48 UTC, tas50 commented on docs/platform/security/vuln/vulnerabilities.md
> +| ![EOL icon](/img/platform/security/eol.png)   | **End-of-life (EOL)** indicates that at least one asset with this CVE is running an operating system version that is no longer supported. |
Currently this actually means it's approaching or at EOl

2024-04-24 16:49 UTC, tas50 commented
It might be better for light mode to get the original SVGs or the risks vs using PNGs that have a background

2024-04-25 03:20 UTC, tas50 commented on docs/platform/security/posture/findings.mdx
> +DEETS
![](https://tenor.com/bZsHJ.gif)

2024-04-26 23:34 UTC, misterpantz commented
> It might be better for light mode to get the original SVGs or the risks vs using PNGs that have a background

Done!

2024-04-27 00:38 UTC, tas50 commented on docs/platform/infra/cloud/azure/azure-integration-scan-group.mdx
> -  Save this JSON content into a file named `mondoo-role.json`:
Was it intentional to update the indent here?

2024-04-27 00:39 UTC, tas50 commented on docs/platform/security/posture/advisories.md
> +1. In the [Mondoo Console](https://console.mondoo.com), [navigate to the space](/platform/start/navigate) in which you want to see vulnerabilities
Should this have a space to match the others?

2024-04-27 00:40 UTC, tas50 commented on docs/platform/security/posture/advisories.md
> +   - To find an advisory related to a specific CVE number, enter all or part of the number. For example, type `2023-21755` or `1325`.
```suggestion
   - To find an advisory related to a specific CVE number, enter all or part of the number. For example, type `2024-21755` or `1325`.
```

2024-04-27 00:41 UTC, tas50 commented on docs/platform/security/posture/findings.mdx
> +Mondoo scores and ranks security findings to help you prioritize fixes to your infrastructure. Our unique algorithms calculates risk score, blast radius, and rank based on a combination of contextual
should this be "calculate"?

2024-04-27 00:43 UTC, tas50 commented on docs/platform/security/posture/findings.mdx
> +For CVEs and advisories, the base score is the [CVSS score](/platform/security/posture/vulnerabilities/#cvss-score-and-metrics).
Do we want to spell out CVSS here similar to CVE above?

2024-04-27 01:19 UTC, misterpantz commented on docs/platform/infra/cloud/azure/azure-integration-scan-group.mdx
> -  Save this JSON content into a file named `mondoo-role.json`:
Nope! Prettier. :(

2024-04-27 01:20 UTC, misterpantz commented on docs/platform/security/posture/advisories.md
> +1. In the [Mondoo Console](https://console.mondoo.com), [navigate to the space](/platform/start/navigate) in which you want to see vulnerabilities
You mean a period? Cuz it needs a period!

2024-04-27 01:21 UTC, misterpantz commented on docs/platform/security/posture/findings.mdx
> +Mondoo scores and ranks security findings to help you prioritize fixes to your infrastructure. Our unique algorithms calculates risk score, blast radius, and rank based on a combination of contextual
Yep! Thanks! Rewrote that sentence too many times.

2024-04-27 01:21 UTC, misterpantz commented on docs/platform/security/posture/findings.mdx
> +For CVEs and advisories, the base score is the [CVSS score](/platform/security/posture/vulnerabilities/#cvss-score-and-metrics).
Ooh yeah.

2024-04-27 01:32 UTC, tas50 commented on docs/platform/security/posture/advisories.md
> +1. In the [Mondoo Console](https://console.mondoo.com), [navigate to the space](/platform/start/navigate) in which you want to see vulnerabilities
That's the word!

2024-04-27 01:33 UTC, tas50 commented on docs/platform/security/posture/advisories.md
> +1. In the [Mondoo Console](https://console.mondoo.com), [navigate to the space](/platform/start/navigate) in which you want to see vulnerabilities
```suggestion
1. In the [Mondoo Console](https://console.mondoo.com), [navigate to the space](/platform/start/navigate) in which you want to see vulnerabilities.
```

2024-04-27 01:34 UTC, tas50 commented on docs/platform/security/posture/findings.mdx
> +Mondoo scores and ranks security findings to help you prioritize fixes to your infrastructure. Our unique algorithms calculates risk score, blast radius, and rank based on a combination of contextual
```suggestion
Mondoo scores and ranks security findings to help you prioritize fixes to your infrastructure. Our unique algorithms calculate risk score, blast radius, and rank based on a combination of contextual risk factors in your environment. You can spend more time closing security gaps and less time sifting through irrelevant or low-priority findings.
```

2024-04-27 03:02 UTC, misterpantz commented on docs/platform/infra/cloud/azure/azure-integration-scan-group.mdx
> -  Save this JSON content into a file named `mondoo-role.json`:
I didn't mean to change this file at all.

2024-04-27 03:16 UTC, tas50 approved these changes

2024-04-27 03:16 UTC, merged