Add MS Defender integration docs
mondoohq/docs pull request #505
Opened 2024-12-11 21:54 UTC by misterpantz

#### Description

Add platform docs on Microsoft Defender for Cloud integration

#### Related issue

none

#### Types of changes

- [ ] Functional documentation bug fix (i.e., broken link or some other busted behavior)
- [ ] New functional doc capabilities (i.e., filter search results)
- [ ] New content
- [ ] Revision to existing content
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

#### Checklist

- [ ] I have read the **README** document about contributing to this repo.
- [ ] I have tested my changes locally and there are no issues.
- [ ] All commits are signed.

2024-12-12 05:48 UTC, czunker reviewed
Thanks @misterpantz

2024-12-12 05:48 UTC, czunker commented on docs/platform/infra/imports/defender.mdx
> +Before you integrate Microsoft Defender for with Mondoo, be sure you have:
There is something missing:
> Microsoft Defender for XXX with Mondoo

2024-12-12 05:48 UTC, czunker commented on docs/platform/infra/imports/defender.mdx
> +4. Select **+ New registration**.
I'm unsure whether the "+" sign is intended or if it is a typo.

2024-12-12 17:31 UTC, misterpantz commented on docs/platform/infra/imports/defender.mdx
> +Before you integrate Microsoft Defender for with Mondoo, be sure you have:
Yes! My cloud disappeared! Thanks. :)

2024-12-12 17:32 UTC, misterpantz commented on docs/platform/infra/imports/defender.mdx
> +4. Select **+ New registration**.
It's intended. Most Azure Add New xxx links/buttons often have a plus sign. This one does.

2024-12-13 05:17 UTC, czunker approved these changes
LGTM

2024-12-13 21:22 UTC, benr requested changes

2024-12-13 21:22 UTC, benr commented on docs/platform/infra/imports/defender.mdx
> +### Step B: Set up authentication for Mondoo
Step B is indented 3 levels, A & B are only 2.

2024-12-13 21:22 UTC, benr commented on docs/platform/infra/imports/defender.mdx
> +#### Create a client secret for Mondoo to authenticate with Microsoft
If the secret and cert methods were named "Option 1" and "Option 2" it might make them more clearly separated.  As written its easy to skim and think your being asked to do both.

2024-12-13 23:20 UTC, misterpantz commented on docs/platform/infra/imports/defender.mdx
> +### Step B: Set up authentication for Mondoo
Thanks!

2024-12-13 23:21 UTC, misterpantz commented on docs/platform/infra/imports/defender.mdx
> +#### Create a client secret for Mondoo to authenticate with Microsoft
I waffled on that! Thanks. I'll do it.

2024-12-16 19:08 UTC, benr approved these changes

2024-12-19 22:45 UTC, merged